version: '3.9'

services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always

  redis:
    image: redis:7.0-alpine
    restart: always
    networks:
      - default
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

networks:
  postgres:
    driver: bridge
    ipam:
      config:
        - subnet: 172.200.0.0/16

volumes:
  cache:
    driver: local
  postgres:
    driver: local